### ISSUE TITLE
Allow Language Selection

### ISSUE THREAD

**Issue by mikebarkmin** [mikebarkmin/lesbar.club#4]
Allow to select a different language. The backend supports at the moment english and german. The supported languages should be fetch from the backend.

**Comment by mikebarkmin** [comment]
Maybe the initial language could be the one of the browser.

**Comment by Abelarm** [comment]
Hi,
I would like to work on this.
I'll start with getting the language from browser. 
(does the UI automatically change if, for example `en_GB` is selected?

**Comment by mikebarkmin** [comment]
I think that I was not very clear. The change of language should result in two different things.

1. The backend should receive that a text is written in a different language that german. Therefore, we must make the[ language key of the json which will be send to the server](https://github.com/mikebarkmin/lesbar.club/blob/46609289d278075bafb059c0a6a1b42e69d21519/server/lesbar/static/index.js#L13) dynamic.

2. Translate the UI. At the moment there is nothing implemented to translate the ui. There are two possible ways to implement that.
  2.1. Client-Side: Use Javascript to store the different locales and translate everything on the client. After a different language is selected we would change the strings with Javascript and no reload would be necessary. Therefore, we have to do most of the work in `index.js`.
  2.2 Server-Side: Use Flasks template engine to translate strings. After a different language is selected we need to refresh the page and send the language information to flask. Therefore, we have to do most of the work in `index.html` and `__init__.py`

**Comment by Abelarm** [comment]
The first point is pretty straightforward, I will select the language based on the browser. Default will be German.

Regarding the second point I think, since right now, there are only two language involved and the amount of text is really small (I count just 9 strings) the client-side option can be a good choice. 

In both case I need a translation of the strings, since I don't speak German :(

**Comment by mikebarkmin** [comment]
|de|en|
|--|--|
|Text|Text|
|Überprüfen|Check|
|Gib den zu prüfenden Text hier ein...|Enter the text to be checked here...|
|Zeichen|Character|
|Buchstaben|Letter|
|Silben|Syllables|
|Sätze|Sentences|
|Wörter|Words|

Flesch-Reading-Ease, Wienersachtext-Formel-4 and Lesbarkeitsindex are names of the metrics. So need to translate them.
